name: tasker
description: Let your device plan your day.

publish_to: 'none'

version: 1.0.0-alpha.1

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  google_sign_in: ^5.0.1
  googleapis: ^2.0.0
  googleapis_auth: ^1.1.0

  firebase_core: ^1.0.3
  firebase_auth: ^1.0.3
  cloud_firestore: ^1.0.4

  flutter_staggered_grid_view: ^0.4.0-nullsafety.3
  path_provider: ^2.0.1
  hive: ^2.0.2
  url_launcher: ^6.0.3
  flutter_svg: ^0.22.0
  #slikker_kit: ^1.1.0-alpha.22
  slikker_kit: 
    path: "../slikker_kit"  

dev_dependencies:
  flutter_launcher_icons: ^0.9.0
  hive_generator: ^1.1.0
  build_runner: ^2.0.3

flutter_icons:
  ios: true
  android: true
  image_path: 'assets/app_icon.png'
  adaptive_icon_foreground: 'assets/app_icon_foreground.png'
  adaptive_icon_background: "#9999FF"

flutter:
  uses-material-design: false #yay!!!!
  assets:
    - assets/google_logo.svg
  fonts:
  - family:  AppIcons
    fonts:
      - asset: fonts/AppIcons.ttf    

  - family: Manrope
    fonts:
      - asset: fonts/Manrope-Bold.ttf